// import type { Metadata } from "next";
// import "./globals.css";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import './globals.css';
import { ReactNode } from 'react';

export const metadata = { title: 'Book Review App' };

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
    <body className="min-h-screen bg-gray-50 text-gray-900">
    <main className="container mx-auto p-6">{children}</main>
    </body>
    </html>
  );
}